docs_dir: docs/book
site_dir: docs/html
extra:
  project: Mezzio
  current_version: v4
  versions:
    - v4
    - v3
    - v2
    - v1
nav:
    - Home: index.md
    - v4:
      - Introduction: v4/intro.md
      - Reference:
        - "Swoole HTTP Server Events": v4/events.md
        - "Static Resources": v4/static-resources.md
        - Logging: v4/logging.md
        - "Async Tasks": v4/async-tasks.md
        - "Using Swoole Tables": v4/table.md
        - "Hot Code Reloading": v4/hot-code-reload.md
        - "Command Line Tooling": v4/command-line.md
        - "How it works": v4/how-it-works.md
        - "Considerations when using Swoole": v4/considerations.md
      - Cookbook:
          - "Removing the StaticResourceRequestListener": v4/cookbook/static-resource-listener-removal.md
          - "Swoole-based server always returns home page": v4/cookbook/swoole-not-starting.md
          - "Provide a unique ID in your request": v4/cookbook/provide-a-request-id.md
      - Migration: v4/migration.md
    - v3:
      - Introduction: v3/intro.md
      - Reference:
        - "Swoole HTTP Server Events": v3/events.md
        - "Static Resources": v3/static-resources.md
        - Logging: v3/logging.md
        - "Async Tasks": v3/async-tasks.md
        - "Using Swoole Tables": v3/table.md
        - "Hot Code Reloading": v3/hot-code-reload.md
        - "Command Line Tooling": v3/command-line.md
        - "How it works": v3/how-it-works.md
        - "Considerations when using Swoole": v3/considerations.md
      - Cookbook:
          - "Removing the StaticResourceRequestListener": v3/cookbook/static-resource-listener-removal.md
          - "Swoole-based server always returns home page": v3/cookbook/swoole-not-starting.md
      - Migration: v3/migration.md
    - v2:
      - Introduction: v2/intro.md
      - Reference:
        - "Static Resources": v2/static-resources.md
        - Logging: v2/logging.md
        - "Async Tasks": v2/async-tasks.md
        - "Using Swoole Tables": v2/table.md
        - "Hot Code Reloading": v2/hot-code-reload.md
        - "Command Line Tooling": v2/command-line.md
        - "How it works": v2/how-it-works.md
        - "Considerations when using Swoole": v2/considerations.md
        - Migration: v2/migration.md
    - v1:
      - Intro: v1/intro.md
      - Reference:
        - "Static Resources": v1/static-resources.md
        - Logging: v1/logging.md
        - "How it works": v1/how-it-works.md
        - "Considerations when using Swoole": v1/considerations.md
    - "_ignore_legacy_pages":
      - "_introduction": intro.md
      - "_static-resources": static-resources.md
      - "_logging": logging.md
      - "_how-it-works": how_it_works.md
site_name: 'mezzio-swoole'
site_description: 'Swoole support for Mezzio'
repo_url: 'https://github.com/mezzio/mezzio-swoole'
